# Generated by Django 3.2.6 on 2022-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
