# Generated by Django 3.2.6 on 2022-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0003_student_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courseid',
            field=models.CharField(max_length=20),
        ),
    ]
